/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aige_cuco_toolproject_jnicallback_AccessMethod */

#ifndef _Included_com_aige_cuco_toolproject_jnicallback_AccessMethod
#define _Included_com_aige_cuco_toolproject_jnicallback_AccessMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aige_cuco_toolproject_jnicallback_AccessMethod
 * Method:    callJavaStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aige_cuco_toolproject_jnicallback_AccessMethod_callJavaStaticMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_aige_cuco_toolproject_jnicallback_AccessMethod
 * Method:    callJavaInstaceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aige_cuco_toolproject_jnicallback_AccessMethod_callJavaInstaceMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_aige_cuco_toolproject_jnicallback_AccessMethod
 * Method:    accessInstanceField
 * Signature: (Lcom/aige/cuco/toolproject/jnicallback/ClassMethod;)V
 */
JNIEXPORT void JNICALL Java_com_aige_cuco_toolproject_jnicallback_AccessMethod_accessInstanceField
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_aige_cuco_toolproject_jnicallback_AccessMethod
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aige_cuco_toolproject_jnicallback_AccessMethod_accessStaticField
  (JNIEnv *, jclass);

/*
 * Class:     com_aige_cuco_toolproject_jnicallback_AccessMethod
 * Method:    callSupperInstanceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aige_cuco_toolproject_jnicallback_AccessMethod_callSupperInstanceMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_aige_cuco_toolproject_jnicallback_AccessMethod
 * Method:    testJNIException
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_aige_cuco_toolproject_jnicallback_AccessMethod_testJNIException
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
