/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aige_cuco_toolproject_JNIUtils */

#ifndef _Included_com_aige_cuco_toolproject_JNIUtils
#define _Included_com_aige_cuco_toolproject_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aige_cuco_toolproject_JNIUtils
 * Method:    getSystemVersionName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aige_cuco_toolproject_JNIUtils_getSystemVersionName
  (JNIEnv *, jobject);

/*
 * Class:     com_aige_cuco_toolproject_JNIUtils
 * Method:    getSystemVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aige_cuco_toolproject_JNIUtils_getSystemVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_aige_cuco_toolproject_JNIUtils
 * Method:    encryption
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aige_cuco_toolproject_JNIUtils_encryption
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_aige_cuco_toolproject_JNIUtils
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_aige_cuco_toolproject_JNIUtils_sumArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_aige_cuco_toolproject_JNIUtils
 * Method:    initInt2DArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_aige_cuco_toolproject_JNIUtils_initInt2DArray
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
